"""init: create all tables

Revision ID: 129188e46db8
Revises: 
Create Date: 2026-03-26 14:32:37.263344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129188e46db8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oe_feedback')
    op.drop_constraint(op.f('fk_oe_ai_estimate_job_project_id_oe_projects_project'), 'oe_ai_estimate_job', type_='foreignkey')
    op.drop_constraint(op.f('fk_oe_ai_estimate_job_user_id_oe_users_user'), 'oe_ai_estimate_job', type_='foreignkey')
    op.drop_constraint(op.f('fk_oe_ai_settings_user_id_oe_users_user'), 'oe_ai_settings', type_='foreignkey')
    op.create_index(op.f('ix_oe_assemblies_component_catalog_resource_id'), 'oe_assemblies_component', ['catalog_resource_id'], unique=False)
    op.create_foreign_key(op.f('fk_oe_assemblies_component_catalog_resource_id_oe_catalog_resource'), 'oe_assemblies_component', 'oe_catalog_resource', ['catalog_resource_id'], ['id'], ondelete='SET NULL')
    op.alter_column('oe_takeoff_document', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_index(op.f('ix_oe_takeoff_document_owner_id'), 'oe_takeoff_document', ['owner_id'], unique=False)
    op.create_index(op.f('ix_oe_takeoff_document_project_id'), 'oe_takeoff_document', ['project_id'], unique=False)
    op.drop_constraint(None, 'oe_takeoff_document', type_='foreignkey')
    op.drop_constraint(None, 'oe_takeoff_document', type_='foreignkey')
    op.create_foreign_key(op.f('fk_oe_takeoff_document_owner_id_oe_users_user'), 'oe_takeoff_document', 'oe_users_user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_oe_takeoff_document_project_id_oe_projects_project'), 'oe_takeoff_document', 'oe_projects_project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_oe_takeoff_document_project_id_oe_projects_project'), 'oe_takeoff_document', type_='foreignkey')
    op.drop_constraint(op.f('fk_oe_takeoff_document_owner_id_oe_users_user'), 'oe_takeoff_document', type_='foreignkey')
    op.create_foreign_key(None, 'oe_takeoff_document', 'oe_users_user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'oe_takeoff_document', 'oe_projects_project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_oe_takeoff_document_project_id'), table_name='oe_takeoff_document')
    op.drop_index(op.f('ix_oe_takeoff_document_owner_id'), table_name='oe_takeoff_document')
    op.alter_column('oe_takeoff_document', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('fk_oe_assemblies_component_catalog_resource_id_oe_catalog_resource'), 'oe_assemblies_component', type_='foreignkey')
    op.drop_index(op.f('ix_oe_assemblies_component_catalog_resource_id'), table_name='oe_assemblies_component')
    op.create_foreign_key(op.f('fk_oe_ai_settings_user_id_oe_users_user'), 'oe_ai_settings', 'oe_users_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_oe_ai_estimate_job_user_id_oe_users_user'), 'oe_ai_estimate_job', 'oe_users_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_oe_ai_estimate_job_project_id_oe_projects_project'), 'oe_ai_estimate_job', 'oe_projects_project', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_table('oe_feedback',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'general'"), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('page_path', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
